import Head from "next/head";
import Education from "../components/Education";
import Experience from "../components/Experience";
import PageContainer from "../components/PageContainer";
import Sidebar from "../components/Sidebar";
import Skills from "../components/Skills";
import Tools from "../components/Tools";

export default function Home() {
  return (
    <div className="flex flex-col lg:w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <div className="flex lg:w-full">
          <Sidebar />
          <div className="mt-80 mb-60 space-y-72 lg:w-full ml-24 lg:ml-0">
            <Experience />
            <Education />
            <Skills />
            <Tools />
          </div>
        </div>
      </PageContainer>
    </div>
  );
}
