import Head from "next/head";
import { ExperienceDesktop, ExperienceMobile } from "../components/Experience";
import Education from "../components/Education";
import PageContainer from "../components/PageContainer";
import Skills from "../components/Skills";
import Tools from "../components/Tools";
import useMediaQuery from "../components/hooks/useMediaQuery";
import Nav from "../components/nav";
import Footer from "../components/Footer";
import Sidebar from "../components/Sidebar";

export default function Home() {
  const isDesktop = useMediaQuery("(min-width: 960px)");

  const DesktopLayout = () => {
    return (
      <PageContainer>
        <div className="flex w-full">
          <Sidebar />
          <div className="mt-72 mb-60 space-y-72 w-full">
            <ExperienceDesktop />
            <Education />
            <Skills />
            <Tools />
          </div>
        </div>
      </PageContainer>
    );
  };
  const MobileLayout = () => {
    return (
      <>
        <div className="flex">
          <Sidebar />
          <div
            className="my-32 space-y-32
          "
          >
            <ExperienceMobile />
            <Education />
            <Skills />
            <Tools />
          </div>
          <Nav />
        </div>
        <Footer />
      </>
    );
  };
  return (
    <div className="flex flex-col lg:w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isDesktop ? <DesktopLayout /> : <MobileLayout />}
    </div>
  );
}
